[[plugins]]
package = "netlify-plugin-a11y"

  # all inputs are optional, we just show you the defaults below
  [plugins.inputs]

  ## Another checkPaths Example 
  checkPaths = [
    '/',
    '/html',
    '/css/properties/grid-template-columns/',
  ]
