[[redirects]]
  from = "/css/selectors/:not()"
  to = "/css/selectors/not"

  from = "/css/selectors/::marker"
  to = "/css/selectors/marker"

  from = "/css/selectors/:nth-child()"
  to = "/css/selectors/nth-child"

  from = "/css/selectors/:nth-last-child()"
  to = "/css/selectors/nth-last-child"
